<template>
  <div>
    <div class="col-md-12 super-banner">
      <h1>釋放你所有的熱情!</h1>
    </div>
    <el-row class="Anton" :style="{textAlign:'center'}">
      <h1>-ABOUT-</h1>
    </el-row>
    <article>
      <div class="col-md-6 offset-md-3">
        G.E.M.鄧紫棋將在 12/27 推出全新專輯《摩天動物園》，昨（18日）舉辦新歌搶聽會，除了先前釋出的冠軍單曲〈句號〉、〈差不多姑娘〉、〈Walk on Water〉、〈摩天動物園〉之外，還與現場媒體與粉絲分享另外其他尚未曝光的新作，在透過歌曲回顧逝去戀情時，讓她忍不住淚灑現場。
        《摩天動物園》是鄧紫棋在今年 3 月告別前公司「蜂鳥音樂」後，僅花費 7 個月便完成的專輯，她現場表示，專輯中每首歌皆代表了一種動物，像是〈差不多姑娘〉透過「孔雀」來隱喻某些人只活在爭奇鬥豔、相互比較的世界裡；〈Walk on Water〉代表了「耶穌蜥蜴」，能夠憑著信心在水面上面走；描述離開前公司的〈句號〉則代表了「蜂鳥」。有網友好奇，〈摩天動物園〉似乎沒聽出有動物？鄧紫棋也在現場給了解答：「其實代表的動物就是『人』。」
      </div>
    </article>
  </div>
</template>
​
<script>
export default {};
</script>
